replicaCount: 1

image:
  repository: ghcr.io/krl4k/ci_cd_helloworld/hello-service
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-credentials

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: "traefik"
  hosts:
    - host: hello-dev.krl4k.com
      paths:
        - path: /api/v1/
          pathType: Prefix
          serviceName: hello-service
          servicePort: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Development-specific PostgreSQL configuration
postgresql:
  primary:
    persistence:
      size: 1Gi  # Smaller size for development
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m

# Development-specific environment variables
env:
  - name: DB_SSL_MODE
    value: "disable"
  - name: DB_MAX_CONNECTIONS
    value: "10"
  - name: DB_CONNECTION_TIMEOUT
    value: "5" 
