version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: hello123
      POSTGRES_DB: hello_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hello"]
      interval: 5s
      timeout: 5s
      retries: 5

  hello-service:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=hello123
      - POSTGRES_DB=hello_db
      - POSTGRES_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: 
