name: Deploy to Dev

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'  # This will trigger on tags like v1.2.3

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container:
      image: dtzar/helm-kubectl:latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          cache: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Determine image tag
        id: tag
        run: |
          # Set default tag for main branch
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_OUTPUT
          else
            # Use tag name for tag events
            echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/hello-service/src
          push: true
          tags: ghcr.io/${{ github.repository }}/hello-service:${{ steps.tag.outputs.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Kubernetes
        run: |
          # Write kubeconfig from secret
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          chmod 600 kubeconfig.yaml
          export KUBECONFIG=$(pwd)/kubeconfig.yaml
          
          # Create namespace if it doesn't exist
          kubectl create namespace dev --dry-run=client -o yaml | kubectl apply -f -
          
          # Deploy/upgrade with Helm
          helm upgrade --install hello-service ./helm/hello-service \
            --namespace dev \
            --values ./helm/hello-service/values.dev.yaml \
            --set image.repository=ghcr.io/${{ github.repository }}/hello-service \
            --set image.tag=${{ steps.tag.outputs.IMAGE_TAG }} \
            --wait --timeout 5m
            
      - name: Verify deployment
        run: |
          kubectl get deployment -n dev hello-service -o wide
          kubectl get pods -n dev -l app=hello-service -o wide
          echo "Deployment completed successfully!"
