name: Deploy to Dev

on:
  push:
    branches:
      - 'main'  # This will trigger on tags like v1.2.3
    tags:
      - 'v*'  # This will trigger on tags like v1.2.3

jobs:
  deploy:
    runs-on: self-hosted
    environment: dev
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push Docker image
        env:
          IMAGE_TAG: ${{ github.ref_name }}  # This will be the tag name (e.g., v1.2.3)
        run: |
          docker build -t ghcr.io/${{ github.repository }}/hello-service:$IMAGE_TAG ./services/hello-service/src
          docker push ghcr.io/${{ github.repository }}/hello-service:$IMAGE_TAG

      - name: Deploy to Kubernetes
        run: |
          # Create kubeconfig with proper permissions
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

          # Deploy using kubectl and helm
          docker run --rm \
            -v ~/.kube:/root/.kube \
            -v $(pwd):/workspace \
            -w /workspace \
            -e KUBECONFIG=/root/.kube/config \
            bitnami/kubectl:latest \
            kubectl create namespace dev --dry-run=client -o yaml | kubectl apply -f -

          docker run --rm \
            -v ~/.kube:/root/.kube \
            -v $(pwd):/workspace \
            -w /workspace \
            -e KUBECONFIG=/root/.kube/config \
            alpine/helm:3.12.0 \
            upgrade --install hello-service ./helm/hello-service \
              --namespace dev \
              --values ./helm/hello-service/values.dev.yaml \
              --set image.repository=ghcr.io/${{ github.repository }}/hello-service \
              --set image.tag=${{ github.ref_name }} \
              --wait
